name: Run unit tests

on: workflow_call

jobs:
  main-job:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-test
      cancel-in-progress: true

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install
        run: npm ci

      - name: Run tests
        run: npm run test:mocha