name: Run tests

on:
  workflow_call

jobs:
  main-job:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
    
    permissions:
      contents: write
      pages: write
      id-token: write
    
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-test
      cancel-in-progress: true

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: "./repo"

      - name: Checkout GH-Pages
        uses: actions/checkout@v4
        with:
          ref: "gh-pages"
          path: "./gh-pages"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install
        run: |
            cd repo
            npm ci

      - run: |
          cd repo
          npm run clean:grammar
      - run: |
          cd repo
          cp ./src/grammar/moocodeLexer.g4 ./
      - run: |
          cd repo
          cp ./src/grammar/moocodeParser.g4 ./
      - run: |
          cd repo
          java -jar ./bin/antlr-4.13.1-complete.jar -Dlanguage=TypeScript ./moocodeLexer.g4
      - run: |
          cd repo
          java -jar ./bin/antlr-4.13.1-complete.jar -Dlanguage=TypeScript -listener -visitor ./moocodeParser.g4
      - run: |
          cd repo
          mkdir ./src/grammar/generated
      - run: |
          cd repo
          mv ./moocode*.ts ./src/grammar/generated

      - name: Run tests with coverage
        run: |
            cd repo
            npm run test-with-coverage

      - run: |
          cd repo
          npm i coverage-badges-cli -g
      - run: |
          cd repo
          npx coverage-badges --source reports/coverage-summary.json --output ./../gh-pages/${{github.ref_name}}/coverage-badge.svg --label="Code Coverage (${{github.ref_name}})"
      
      - run: |
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *
          git commit -m "Automated gh-pages content update"
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './gh-pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4