name: Automated Checks (pull request)

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, synchronize]

jobs:
  lint:
    uses: ./.github/workflows/action_check-lint.yml
  
  unit-tests:
    uses: ./.github/workflows/action_unit-tests.yml
  
  ensure-new-version:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-version
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Trust PSGallery and install requirements
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PowerShellForGitHub

      - name: Ensure newer version than last release
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        shell: pwsh
        run: |
          Import-Module -Force './scripts/common.psm1'
          EnsureNewVersion

      - name: Ensure latest version tag points to latest commit
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        shell: pwsh
        run: |
          Import-Module -Force './scripts/common.psm1'
          EnsureLatestVersionTagPointsToLatestCommit