name: Automated Checks (dev)

on:
  push:
    branches: [dev]

jobs:
  lint:
    uses: ./.github/workflows/check-lint.yml
  
  test:
    permissions:
      contents: write
      pages: write
      id-token: write

    uses: ./.github/workflows/check-tests.yml
